name: Docker-build
on:
  push:
    branches:
      - master
      - dev

env:
  BUILDKIT_IMAGE: jkaninda/kafka-kraft
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      -
        name: Build and push 3.4
        uses: docker/build-push-action@v3
        with:
          file: "./docker/Dockerfile"
          push: true
          tags: |
           "${{env.BUILDKIT_IMAGE}}:2.8.1"
           "${{env.BUILDKIT_IMAGE}}:dev"